default: &default
  adapter: postgresql
  encoding: unicode
  pool: 20
  timeout: 3000
  username:
  password:

development:
  <<: *default
  database: barcode_development

test:
  <<: *default
  database: barcode_test

production:
  <<: *default
  database: barcode_production
